---
- name: Update web servers
  hosts: _Node0, _Node1

  tasks:
  - name: Create text file
    copy:
      content: 'I am a text file I exist on the nodes'
      dest: ~/myTextFile.txt
  - name: Compress the file
    archive:
      path: ~/myTextFile.txt
      dest: ~/myTextFile.tar.gz
      remove: yes 
  - name: Get my IP
    get_url: 
      url: http://icanhazip.com
      dest: ~/index.html   
