---
- name: Setup Docker and ngnx
  hosts: 
    _rhel, 
    _ubuntu, 
  remote_user: "{{ 'ubuntu' if tags.server_type  == 'ubuntu'  else 'ec2-user' }}"

  #hosts: _rhel_node
  #remote_user: ec2-user

  roles:
  - docker_role
  - ngnx_role

