---
- name: Setup Docker
  hosts: _Node0, _Node1
  #remote_user: root

  tasks:
  - name: Update  package index
    #ansible.builtin.shell: sudo apt-get update
    become: yes
    apt:
      update_cache: yes
  - name: Install packages
    #ansible.builtin.shell: sudo apt-get install ca-certificates curl gnupg lsb-release
    become: yes
    apt:
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release  
  - name: Add Docker’s official GPG key
    ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - name: set up the repository
    ansible.builtin.shell: >
      echo  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - name: Update  package index
    #ansible.builtin.shell: sudo apt-get update     
    become: yes
    apt:
      update_cache: yes
  - name: Install docker
    become: yes
    apt:
      pkg:
      - docker-ce 
      - docker-ce-cli
      - containerd.io  
  - name: Install ngnx
    become: yes
    ansible.builtin.shell: sudo docker run -d -p 8080:80 nginx
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted       
